version: '3.4'

services:
  apartments.api:
    image: ${DOCKER_REGISTRY-}apartmentsapi
    build:
      context: .
      dockerfile: Services/Apartments/Apartments.API/Dockerfile

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
