version: '3.4'

services:
  apartments.api:
    image: ${DOCKER_REGISTRY-}apartmentsapi
    build:
     context: .
     dockerfile: Services/Apartments/Apartments.API/Dockerfile
    ports:
    - 8000:8000
    - 8004:8004

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
     - 27017:27017
    volumes:
    - local:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8079:8079
      - 808
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    volumes:
      - local:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  rooms.api:
    image: ${DOCKER_REGISTRY-}roomsapi
    build:
      context: .
      dockerfile: Services/Rooms/Rooms.Api/Dockerfile
    ports:
    - 8001:8001
    - 8005:8005


  tenants.api:
    image: ${DOCKER_REGISTRY-}tenantsapi
    build:
      context: .
      dockerfile: Services/Tenants/Tenants.Api/Dockerfile
    ports:
    - 8002:8002
    - 8006:8006

  statistics.api:
    image: ${DOCKER_REGISTRY-}statisticsapi
    build:
      context: .
      dockerfile: Services/Statistics/Statistics.Api/Dockerfile
    ports:
    - 8003:8003
    - 8007:8007

volumes:
  local:






